### ISSUE TITLE
Change of Domain Ownership

### ISSUE THREAD

**Issue by majulahsingapuri** [bhargav95/bhargav95.github.io#2]
Hey this might be a bit of a weird request but I have bought over your domain bhargav.io and it seems that the domain still points to your site and prevents me from publishing my site instead. It'd be great if you could deregister the site from your verified domains so i use it instead. thanks.

**Comment by bhargav95** [comment]
Done, verified the domain no longer loads.

**Comment by majulahsingapuri** [comment]
i think you might have to remove the CNAME file as well by changing the custom domains setting under the Pages tab. Github uses that internally to route requests

**Comment by bhargav95** [comment]
> i think you might have to remove the CNAME file as well by changing the custom domains setting under the Pages tab. Github uses that internally to route requests

Done!
